### ISSUE TITLE
httparty doesn't get installed

### ISSUE THREAD

**Issue by brandonzylstra** [solutious/stella#2]
I just installed Stella, and then tried to use it, and got `cannot load such file -- httparty (LoadError)`:

```
$ stella preview -p stella.rb
/Users/curtcoty/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- httparty (LoadError)
    from /Users/curtcoty/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /Users/curtcoty/.rvm/gems/ruby-2.1.2/gems/stella-2.1.2.004/lib/stella.rb:17:in `<top (required)>'
    from /Users/curtcoty/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/curtcoty/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /Users/curtcoty/.rvm/gems/ruby-2.1.2/gems/stella-2.1.2.004/bin/stella:24:in `<top (required)>'
    from /Users/curtcoty/.rvm/gems/ruby-2.1.2/bin/stella:23:in `load'
    from /Users/curtcoty/.rvm/gems/ruby-2.1.2/bin/stella:23:in `<main>'
    from /Users/curtcoty/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/curtcoty/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

Installing `httparty` on the command line gets around that problem.

**Comment by brandonzylstra** [comment]
I don't see `httparty` anywhere in the Gemspec: https://github.com/solutious/stella/blob/master/stella.gemspec
